function orgt(s) {return binl2hex(core_hx(str2binl(s), s.length * chrsz))};

var bookConfig = {
  "CreatedTime":"2023-03-10113026",
  "CreatedVersion":"6.22.6",
  "ClientBookId":"1678447826365",
  "productName":"Flip PDF Plus",
  "productVersion":"6.22.6",
  "homePage":"https://www.flipbuilder.com/",
  "totalPageCount":636,
  "largePageWidth":989,
  "largePageHeight":1280,
  "BookTemplateName":"Metro",
  "BookThemeName":"Default",
  "SlideshowAutoPlay":false,
  "SlideshowPlayInterval":5,
  "language":"English",
  "AboutAddress":"",
  "AboutEmail":"",
  "AboutMobile":"",
  "AboutWebsite":"",
  "AboutDescription":"",
  "AboutAuthor":"",
  "searchPositionJS":"files/search/text_position[%d].js",
  "normalPath":"files/page/",
  "largePath":"files/page/",
  "thumbPath":"files/thumb/",
  "isHasPdf":1,
  "canvasRender":false,
  "flipshortcutbutton":"Show",
  "phoneFlipShortcutButton":false,
  "appLogoIcon":"files/extfile/appLogoIcon.png",
  "appLogoLinkURL":"",
  "logoPadding":30,
  "logoHeight":25,
  "bgBeginColor":"#505050",
  "bgEndColor":"#505050",
  "bgMRotation":30,
  "backGroundImgURL":"",
  "backgroundPosition":"Stretch",
  "backgroundOpacity":"100",
  "backgroundScene":"None",
  "BackgroundSoundButtonVisible":"Show",
  "FlipSound":"Yes",
  "BackgroundSoundURL":"",
  "BackgroundSoundLoop":"-1",
  "bgSoundVol":"50",
  "loadingCaption":"Smart Vietnam",
  "loadingCaptionFontSize":20,
  "loadingCaptionColor":"#DDDDDD",
  "loadingPicture":"",
  "loadingPictureHeight":150,
  "loadingBackground":"#323232",
  "showLoadingGif":"Yes",
  "loadingDisplayTime":"0",
  "loadingVideo":"",
  "ToolBarVisible":"Yes",
  "toolbarColor":"#333333",
  "iconColor":"#EEEEEE",
  "pageNumColor":"#1B2930",
  "iconFontColor":"#EEEEEE",
  "formFontColor":"#EEEEEE",
  "formBackgroundColor":"#3963A5",
  "ToolBarAlpha":0.8,
  "HomeButtonVisible":false,
  "HomeURL":"%1%",
  "aboutButtonVisible":false,
  "aboutContactInfoTxt":"",
  "enablePageBack":"Hide",
  "ShareButtonVisible":true,
  "addCurrentPage":false,
  "ThumbnailsButtonVisible":true,
  "ThumbnailSize":"small",
  "BookMarkButtonVisible":true,
  "TableOfContentButtonVisible":true,
  "isHideTabelOfContentNodes":false,
  "SearchButtonVisible":"Show",
  "leastSearchChar":"2",
  "searchFontColor":"#FFFFFF",
  "searchKeywordFontColor":"#FFB000",
  "searchHightlightColor":"#FDC606",
  "SelectTextButtonVisible":false,
  "SelectTextButtonIcon":"",
  "WeChatShareButtonVisible":false,
  "WeChatShareButtonIcon":"",
  "OnlyOpenInWechat":false,
  "NoWechatSharing":false,
  "PrintButtonVisible":false,
  "printWatermarkFile":"",
  "AutoPlayButtonVisible":"Show",
  "autoPlayAutoStart":false,
  "autoPlayDuration":"3",
  "autoPlayLoopCount":"1",
  "DownloadButtonVisible":false,
  "DownloadURL":"",
  "downloadConfig":"",
  "PhoneButtonVisible":"Hide",
  "PhoneButtonIcon":"",
  "PhoneNumbers":"",
  "ZoomButtonVisible":true,
  "SupportOperatePageZoom":"Yes",
  "middleZoomWidth":"0",
  "mouseWheelFlip":"yes",
  "ZoomMapVisible":"Hide",
  "EmailButtonVisible":false,
  "btnShareWithEmailSubject":"",
  "btnShareWithEmailBody":"{link}",
  "MagnifierButtonVisible":"Hide",
  "FullscreenButtonVisible":"Show",
  "AnnotationButtonVisible":false,
  "showGotoButtonsAtFirst":false,
  "buttonsSortXML":[
    "thumb",
    "table",
    "goto",
    "zoom",
    "bookmark",
    "number",
    "sound",
    "search",
    "print",
    "annotation",
    "wechat",
    "email",
    "btnshare",
    "download",
    "language",
    "home",
    "autoflip",
    "select",
    "about",
    "report",
    "doublesinglepage"
  ],
  "QRCode":false,
  "LeftShadowWidth":0,
  "LeftShadowAlpha":"1",
  "RightShadowWidth":0,
  "RightShadowAlpha":"1",
  "ShowTopLeftShadow":"false",
  "pageHighlightType":"book",
  "HardPageEnable":"No",
  "hardCoverBorderWidth":"8",
  "borderColor":"#572F0D",
  "cornerRound":"8",
  "outerCoverBorder":"Yes",
  "pageBackgroundColor":"#FFFFFF",
  "BindingType":"side",
  "thicknessWidthType":"thick",
  "bookPageStretch":false,
  "thicknessColor":"#FFFFFF",
  "textClarityEnhancement":"0",
  "totalPagesCaption":"",
  "pageNumberCaption":"",
  "hideMiniFullscreen":false,
  "maxWidthToSmallMode":"400",
  "maxHeightToSmallMode":"350",
  "FlipStyle":"Flip",
  "FlipDirection":"0",
  "supportSerialsFlip":false,
  "flippingTime":"0.3",
  "RightToLeft":false,
  "BanFlipFromDirection":false,
  "isTheBookOpen":false,
  "SingleModeBanFlipToLastPage":false,
  "showThicknessOnMobile":false,
  "autoDoublePage":"auto",
  "DoubleSinglePageButtonVisible":false,
  "topMargin":10,
  "bottomMargin":10,
  "leftMargin":10,
  "rightMargin":10,
  "retainBookCenter":"Yes",
  "isSingleBookFullWindowOnMobile":false,
  "topMarginOnMobile":"0",
  "bottomMarginOnMobile":"0",
  "leftMarginOnMobile":"0",
  "rightMarginOnMobile":"0",
  "toolbarAlwaysShow":false,
  "showHelpContentAtFirst":false,
  "InstructionsButtonVisible":"Show",
  "showBookInstructionOnStart":false,
  "showInstructionOnStart":false,
  "CurlingPageCorner":"Yes",
  "leftRightPnlShowOption":"None",
  "restorePageVisible":false,
  "appLargeLogoIcon":"",
  "appLargeLogoURL":"",
  "LargeLogoPosition":"top-left",
  "isFixLogoSize":false,
  "logoFixWidth":"0",
  "logoFixHeight":"0",
  "isStopMouseMenu":"yes",
  "useTheAliCloudChart":false,
  "highDefinitionConversion":false,
  "updateURLForPage":true,
  "googleAnalyticsID":"UA-87479-1",
  "OnlyOpenInIframe":"No",
  "OnlyOpenInIframeInfo":"No reading rights",
  "OpenWindow":"Blank",
  "showLinkHint":"No",
  "outputSetting":"",
  "shotPic":"",
  "bookTitle":"FLIPBOOK",
  "thumbnailColor":"#333333",
  "thumbnailAlpha":70,
  "randomString":"uJ7J1VTcwkZfvlcy",
  "securityType":1,
  "singlePasswordMD5":"",
  "singlePasswordKey":"",
  "excludeFrontPages":"0",
  "passwardPrompt":"",
  "isShowAssistantPerson":true,
  "mainPDF":"files/profile 17.11.23.pdf"
};

var language = [
  {
    "language":"English",
    "btnFirstPage":"First",
    "btnNextPage":"Next Page",
    "btnLastPage":"Last",
    "btnPrePage":"Previous Page",
    "btnDownload":"Download",
    "btnPrint":"Print",
    "btnSearch":"Search",
    "btnClearSearch":"Clear",
    "frmSearchPrompt":"Clear",
    "btnBookMark":"Table of contents",
    "btnHelp":"Help",
    "btnHome":"Home",
    "btnFullScreen":"Enable FullScreen",
    "btnDisableFullScreen":"Disable FullScreen",
    "btnSoundOn":"Sound On",
    "btnSoundOff":"Sound Off",
    "btnShareEmail":"Share",
    "btnSocialShare":"Social Share",
    "btnZoomIn":"Zoom In",
    "btnZoomOut":"Zoom Out",
    "btnDragToMove":"Move by mouse drag",
    "btnAutoFlip":"Auto Flip","btnStopAutoFlip":"Stop Auto Flip","btnGoToHome":"Return Home","frmHelpCaption":"Help","frmHelpTip1":"Double click to zoom in or out",
    "frmHelpTip2":"Drag the page corner to view","frmPrintCaption":"Print","frmPrintBtnCaption":"Print","frmPrintPrintAll":"Print All Pages",
    "frmPrintPrintCurrentPage":"Print Current Page","frmPrintPrintRange":"Print Range","frmPrintExampleCaption":"Example: 2,5,8-26","frmPrintPreparePage":"Preparing Page:",
    "frmPrintPrintFailed":"Print Failed:","pnlSearchInputInvalid":"Your search content must be at least 2 characters long.",
    "loginCaption":"Login","loginInvalidPassword":"Not a valid password!",
    "loginPasswordLabel":"Password:",
    "loginBtnLogin":"Login","loginBtnCancel":"Cancel","btnThumb":"Thumbnails","lblPages":"Pages:","lblPagesFound":"Pages:",
    "lblPageIndex":"Page","btnAbout":"About","frnAboutCaption":"About &amp; Contact","btnSinglePage":"Single Page","btnDoublePage":"Double Page",
    "btnSwicthLanguage":"Switch Language","tipChangeLanguage":"Please select a language below...","btnMoreOptionsLeft":"More Options",
    "btnMoreOptionsRight":"More Options","btnFit":"Fit Window","smallModeCaption":"Click to view in fullscreen",
    "btnAddAnnotation":"Add Annotations","btnAnnotation":"Annotations","FlipPageEditor_SaveAndExit":"Save and Exit","FlipPageEditor_Exit":"Exit","DrawToolWindow_Redo":"Redo","DrawToolWindow_Undo":"Undo","DrawToolWindow_Clear":"Clear","DrawToolWindow_Brush":"Brush","DrawToolWindow_Width":"Width","DrawToolWindow_Alpha":"Alpha","DrawToolWindow_Color":"Color","DrawToolWindow_Eraser":"Eraser","DrawToolWindow_Rectangular":"Rectangular","DrawToolWindow_Ellipse":"Ellipse","TStuff_BorderWidth":"Border Width","TStuff_BorderAlph":"Border Alpha","TStuff_BorderColor":"Border Color","DrawToolWindow_TextNote":"Text Note","AnnotMark":"Bookmarks","lastpagebtnHelp":"Last page","firstpagebtnHelp":"First page","homebtnHelp":"Return to home page","aboubtnHelp":"About","screenbtnHelp":"Open this application in full-screen mode","helpbtnHelp":"Show help","searchbtnHelp":"Search from pages","pagesbtnHelp":"Take a look at the thumbnail of this brochure","bookmarkbtnHelp":"Open Bookmarks","AnnotmarkbtnHelp":"Open Table of contents","printbtnHelp":"Print the brochure","soundbtnHelp":"Turn on or off the sound","sharebtnHelp":"Send Email to","socialSharebtnHelp":"Social Share","zoominbtnHelp":"Zoom in","downloadbtnHelp":"Downdlaod this brochure","pagemodlebtnHelp":"Switch Single and double page mode","languagebtnHelp":"Switch Lauguage","annotationbtnHelp":"Add Annotation","addbookmarkbtnHelp":"Add Bookmark","removebookmarkbtnHelp":"Remove Bookmark","updatebookmarkbtnHelp":"Update Bookmark","btnShoppingCart":"Shopping Cart","Help_ShoppingCartbtn":"Shopping Cart","Help_btnNextPage":"Next page","Help_btnPrePage":"Previous page","Help_btnAutoFlip":"Auto filp","Help_StopAutoFlip":"Stop atuo filp","btnaddbookmark":"Add","btndeletebookmark":"Delete","btnupdatebookmark":"Update","frmyourbookmarks":"Your bookmarks","frmitems":"items","DownloadFullPublication":"This Publication","DownloadCurrentPage":"Include Current Page","DownloadAttachedFiles":"Attached Files","lblLink":"Link","btnCopy":"Copy Button","infCopyToClipboard":"Your browser dose not support clipboard, please do it yourself.","restorePage":"Would you like to restore previous session","tmpl_Backgoundsoundon":"Background Sound On","tmpl_Backgoundsoundoff":"Background Sound Off","tmpl_Flipsoundon":"Flip Sound On","tmpl_Flipsoundoff":"Flip Sound Off","Help_PageIndex":"The current page number","tmpl_PrintPageRanges":"PAGE RANGES","tmpl_PrintPreview":"PREVIEW","btnSelection":"Select Text","loginNameLabel":"Name:","btnGotoPage":"Go","btnSettings":"Setting","soundSettingTitle":"Sound Setting","closeFlipSound":"Turn Off Flip Sound","closeBackgroundSound":"Turn Off Backgorund Sound","frmShareCaption":"Share","frmShareLinkLabel":"Link:","frmShareBtnCopy":"Copy","frmShareItemsGroupCaption":"Social Share","frmPanelTitle":"Share it","frmShareQRcode":"QRCode","TAnnoActionPropertyStuff_GotoPage":"Go to page","btnPageBack":"Backward","btnPageForward":"Forward","SelectTextCopy":"Copy Selected Text","selectCopyButton":"Copy","TStuffCart_TypeCart":"Shopping Cart","TStuffCart_DetailedQuantity":"Quantity","TStuffCart_DetailedPrice":"Price","ShappingCart_Close":"Close","ShappingCart_CheckOut":"Checkout","ShappingCart_Item":"Item","ShappingCart_Total":"Total","ShappingCart_AddCart":"Add to cart","ShappingCart_InStock":"In Stock","TStuffCart_DetailedCost":"Shipping cost","TStuffCart_DetailedTime":"Delivery time","TStuffCart_DetailedDay":"day(s)","ShappingCart_NotStock":"Not enough in stock","btnCrop":"Crop","btnDragButton":"Drag","btnFlipBook":"Flip Book","btnSlideMode":"Slide Mode","btnSinglePageMode":"Single Page Mode","btnVertical":"Vertical Mode","btnHotizontal":"Horizontal Mode","btnClose":"Close","btnBookStatus":"Book View","checkBoxInsert":"Insert Current Page","lblLast":"This is the last page.","lblFirst":"This is the first page.","lblFullscreen":"Click to view in fullscreen","lblName":"Name","lblPassword":"Password","lblLogin":"Login","lblCancel":"Cancel","lblNoName":"User name can not be empty.","lblNoPassword":"Password can not be empty.","lblNoCorrectLogin":"Please enter the correct user name and password.","lblNoCorrectPass":"Please enter the correct password.","btnVideo":"Video Gallery","btnSlideShow":"Slide Show","btnPositionToMove":"Move by mouse position","lblHelp1":"Drag the page corner to view","lblHelp2":"Double click to zoom in, out","lblCopy":"Copy","lblAddToPage":"add to page","lblPage":"Page","lblTitle":"Title","lblEdit":"Edit","lblDelete":"Delete","lblRemoveAll":"Remove All","tltCursor":"cursor","tltAddHighlight":"add highlight","tltAddTexts":"add texts","tltAddShapes":"add shapes","tltAddNotes":"add notes","tltAddImageFile":"add image file","tltAddSignature":"add signature","tltAddLine":"add line","tltAddArrow":"add arrow","tltAddRect":"add rect","tltAddEllipse":"add ellipse",
    "lblDoubleClickToZoomIn":"Double click to zoom in.","frmShareLabel":"Share","frmShareInfo":"You can easily share this publication to social networks.Just click the appropriate button below","frminsertLabel":"Insert to Site","frminsertInfo":"Use the code below to embed this publication to your website.","btnQRCode":"Click to scan QR code","btnRotateLeft":"Rotate Left","btnRotateRight":"Rotate Right","lblSelectMode":"Select view mode please.","frmDownloadPreview":"Preview","frmHowToUse":"How To Use","lblHelpPage1":"Move your finger to flip the book page.","lblHelpPage2":"Zoom in by using gesture or double click on the page.","lblHelpPage3":"Click on the logo to reach the official website of the company.","lblHelpPage4":"Add bookmarks, use search function and auto flip the book.","lblHelpPage5":"Switch horizontal and vertical view on mobile devices.","TTActionQuiz_PlayAgain":"Do you wanna play it again","TTActionQuiz_Ration":"Your ratio is","frmTelephone":"Tel","btnDialing":"Call","lblSelectMessage":"Please copy the the text content in the text box.","btnSelectText":"Select Text","btnNote":"Annotation","btnPhoneNumber":"Tel","btnWeCharShare":"WeChat Share","btnMagnifierIn":"Magnifying Glass","btnMagnifierOut":"Magnifier Reduction","frmShareSmallProgram":"smallProgram","btnMagnifier":"Magnifier","frmPrintPrintLimitFailed":"Sorry, you can't print the pages.","infNotSupportHtml5":"HTML5 is not supported by your current web browser, please read the book with latest verson web browser. Here we recommend you to read it with Chrome.","btnReport":"Report","btnDoubleSinglePage":"Page switch","frmBookMark":"Bookmark","btnFullscreen":"Fullscreen","btnExitFullscreen":"Exit Fullscreen","btnMore":"More","frmPrintall":"Print All Pages","frmPrintcurrent":"Print Current Page","frmPrintRange":"Print Range","frmPrintexample":"Example: 2,3,5-10","frmPrintbtn":"Print","frmaboutcaption":"Contact","frmaboutcontactinformation":"Contact Information","frmaboutADDRESS":"Address","frmaboutEMAIL":"Email","frmaboutWEBSITE":"Website","frmaboutMOBILE":"Mobile","frmaboutAUTHOR":"Author","frmaboutDESCRIPTION":"Description","frmSearch":"Search","frmToc":"Table of Contents","btnTableOfContent":"Table of Contents","lblDescription":"Title","frmLinkLabel":"Link","frmQrcodeCaption":"Scan the bottom two-dimensional code to view with mobile phone.","btnLanguage":"Change Language","msgConfigMissing":"Configuration file is missing, unable to open the book.","lblSave":"Save","frmSharePanelTitle":"Share it","btnDownloadPosterPrompt":"Click to download the poster","infLongPressToSavePoster":"Press and hold to save the poster","infLongPressToIndentify":"Long press to identify QR code","infScanCodeToView":"Scan code to read","lblConfirm":"Confirm","infDeleteNote":"Do you want to delete this note?","btnBack":"Back","proFullScreenWarn":"Current browser does not support full-screen,Please use Chrome for best results.","frmVideoListTitle":"Video list","frmVideoTitle":"Video"}];

var fliphtml5_pages = [
  {"l":"files/page/1.jpg","t":"files/thumb/1.jpg"},{"p":"none","l":"files/page/2.jpg","t":"files/thumb/2.jpg"},{"l":"files/page/3.jpg","t":"files/thumb/3.jpg"},
  {"l":"files/page/4.jpg","t":"files/thumb/4.jpg"},{"l":"files/page/5.jpg","t":"files/thumb/5.jpg"},{"l":"files/page/6.jpg","t":"files/thumb/6.jpg"},
  {"l":"files/page/7.jpg","t":"files/thumb/7.jpg"},{"l":"files/page/8.jpg","t":"files/thumb/8.jpg"},{"l":"files/page/9.jpg","t":"files/thumb/9.jpg"},
  {"l":"files/page/10.jpg","t":"files/thumb/10.jpg"},{"l":"files/page/11.jpg","t":"files/thumb/11.jpg"},{"l":"files/page/12.jpg","t":"files/thumb/12.jpg"},
  {"l":"files/page/13.jpg","t":"files/thumb/13.jpg"},{"l":"files/page/14.jpg","t":"files/thumb/14.jpg"},{"l":"files/page/15.jpg","t":"files/thumb/15.jpg"},
  {"l":"files/page/16.jpg","t":"files/thumb/16.jpg"},{"l":"files/page/17.jpg","t":"files/thumb/17.jpg"},{"l":"files/page/18.jpg","t":"files/thumb/18.jpg"},
  {"l":"files/page/19.jpg","t":"files/thumb/19.jpg"},{"l":"files/page/20.jpg","t":"files/thumb/20.jpg"},{"l":"files/page/21.jpg","t":"files/thumb/21.jpg"},
  {"l":"files/page/22.jpg","t":"files/thumb/22.jpg"},{"l":"files/page/23.jpg","t":"files/thumb/23.jpg"},{"l":"files/page/24.jpg","t":"files/thumb/24.jpg"},
  {"l":"files/page/25.jpg","t":"files/thumb/25.jpg"},{"l":"files/page/26.jpg","t":"files/thumb/26.jpg"},{"l":"files/page/27.jpg","t":"files/thumb/27.jpg"},
  {"l":"files/page/28.jpg","t":"files/thumb/28.jpg"},{"l":"files/page/29.jpg","t":"files/thumb/29.jpg"},{"l":"files/page/30.jpg","t":"files/thumb/30.jpg"},
  {"l":"files/page/31.jpg","t":"files/thumb/31.jpg"},{"l":"files/page/32.jpg","t":"files/thumb/32.jpg"},{"l":"files/page/33.jpg","t":"files/thumb/33.jpg"},
  {"l":"files/page/34.jpg","t":"files/thumb/34.jpg"},{"l":"files/page/35.jpg","t":"files/thumb/35.jpg"},{"l":"files/page/36.jpg","t":"files/thumb/36.jpg"},
  {"l":"files/page/37.jpg","t":"files/thumb/37.jpg"},{"l":"files/page/38.jpg","t":"files/thumb/38.jpg"},{"l":"files/page/39.jpg","t":"files/thumb/39.jpg"},
  {"l":"files/page/40.jpg","t":"files/thumb/40.jpg"},{"l":"files/page/41.jpg","t":"files/thumb/41.jpg"},{"l":"files/page/42.jpg","t":"files/thumb/42.jpg"},
  {"l":"files/page/43.jpg","t":"files/thumb/43.jpg"},{"l":"files/page/44.jpg","t":"files/thumb/44.jpg"},{"l":"files/page/45.jpg","t":"files/thumb/45.jpg"},
  {"l":"files/page/46.jpg","t":"files/thumb/46.jpg"},{"l":"files/page/47.jpg","t":"files/thumb/47.jpg"},{"l":"files/page/48.jpg","t":"files/thumb/48.jpg"},
  {"l":"files/page/49.jpg","t":"files/thumb/49.jpg"},{"l":"files/page/50.jpg","t":"files/thumb/50.jpg"},{"l":"files/page/51.jpg","t":"files/thumb/51.jpg"},
  {"l":"files/page/52.jpg","t":"files/thumb/52.jpg"},{"l":"files/page/53.jpg","t":"files/thumb/53.jpg"},{"l":"files/page/54.jpg","t":"files/thumb/54.jpg"},
  {"l":"files/page/55.jpg","t":"files/thumb/55.jpg"},{"l":"files/page/56.jpg","t":"files/thumb/56.jpg"},{"l":"files/page/57.jpg","t":"files/thumb/57.jpg"},
  {"l":"files/page/58.jpg","t":"files/thumb/58.jpg"},{"l":"files/page/59.jpg","t":"files/thumb/59.jpg"},{"l":"files/page/60.jpg","t":"files/thumb/60.jpg"},
  {"l":"files/page/61.jpg","t":"files/thumb/61.jpg"},{"l":"files/page/62.jpg","t":"files/thumb/62.jpg"},{"l":"files/page/63.jpg","t":"files/thumb/63.jpg"},
  {"l":"files/page/64.jpg","t":"files/thumb/64.jpg"},{"l":"files/page/65.jpg","t":"files/thumb/65.jpg"},{"l":"files/page/66.jpg","t":"files/thumb/66.jpg"},
  {"l":"files/page/67.jpg","t":"files/thumb/67.jpg"},{"l":"files/page/68.jpg","t":"files/thumb/68.jpg"},{"l":"files/page/69.jpg","t":"files/thumb/69.jpg"},
  {"l":"files/page/70.jpg","t":"files/thumb/70.jpg"},{"l":"files/page/71.jpg","t":"files/thumb/71.jpg"},{"l":"files/page/72.jpg","t":"files/thumb/72.jpg"},
  {"l":"files/page/73.jpg","t":"files/thumb/73.jpg"},{"l":"files/page/74.jpg","t":"files/thumb/74.jpg"},{"l":"files/page/75.jpg","t":"files/thumb/75.jpg"},
  {"l":"files/page/76.jpg","t":"files/thumb/76.jpg"},{"l":"files/page/77.jpg","t":"files/thumb/77.jpg"},{"l":"files/page/78.jpg","t":"files/thumb/78.jpg"},
  {"l":"files/page/79.jpg","t":"files/thumb/79.jpg"},{"l":"files/page/80.jpg","t":"files/thumb/80.jpg"},{"l":"files/page/81.jpg","t":"files/thumb/81.jpg"},
  {"l":"files/page/82.jpg","t":"files/thumb/82.jpg"},{"l":"files/page/83.jpg","t":"files/thumb/83.jpg"},{"l":"files/page/84.jpg","t":"files/thumb/84.jpg"},
  {"l":"files/page/85.jpg","t":"files/thumb/85.jpg"},{"l":"files/page/86.jpg","t":"files/thumb/86.jpg"},{"l":"files/page/87.jpg","t":"files/thumb/87.jpg"},
  {"l":"files/page/88.jpg","t":"files/thumb/88.jpg"},{"l":"files/page/89.jpg","t":"files/thumb/89.jpg"},{"l":"files/page/90.jpg","t":"files/thumb/90.jpg"},
  {"l":"files/page/91.jpg","t":"files/thumb/91.jpg"},{"l":"files/page/92.jpg","t":"files/thumb/92.jpg"},{"l":"files/page/93.jpg","t":"files/thumb/93.jpg"},
  {"l":"files/page/94.jpg","t":"files/thumb/94.jpg"},{"l":"files/page/95.jpg","t":"files/thumb/95.jpg"},{"l":"files/page/96.jpg","t":"files/thumb/96.jpg"},
  {"l":"files/page/97.jpg","t":"files/thumb/97.jpg"},{"l":"files/page/98.jpg","t":"files/thumb/98.jpg"},{"l":"files/page/99.jpg","t":"files/thumb/99.jpg"},
  {"l":"files/page/100.jpg","t":"files/thumb/100.jpg"},{"l":"files/page/101.jpg","t":"files/thumb/101.jpg"},{"l":"files/page/102.jpg","t":"files/thumb/102.jpg"},
  {"l":"files/page/103.jpg","t":"files/thumb/103.jpg"},{"l":"files/page/104.jpg","t":"files/thumb/104.jpg"},{"l":"files/page/105.jpg","t":"files/thumb/105.jpg"},
  {"l":"files/page/106.jpg","t":"files/thumb/106.jpg"},{"p":"none","l":"files/page/107.jpg","t":"files/thumb/107.jpg"},{"l":"files/page/108.jpg","t":"files/thumb/108.jpg"}
];

var ols = [
  {"caption":"0-Front Cover-EN","url":"","page":"3","level":"1","children":[]},
  {"caption":"00-Intro-EN","url":"","page":"3","level":"1","children":[]},
  {"caption":"01-EAS-EN","url":"","page":"14","level":"1","children":[]},
  {"caption":"02-Monitor Mounts-EN","url":"","page":"58","level":"1","children":[]},
  {"caption":"03-Compression-EN","url":"","page":"88","level":"1","children":[]},
  {"caption":"04-Cam Latches-EN","url":"","page":"148","level":"1","children":[]},
  {"caption":"05-Locks-EN","url":"","page":"190","level":"1","children":[]},
  {"caption":"06-Multi-Point-EN","url":"","page":"206","level":"1","children":[]},
  {"caption":"07-Push to Close-EN","url":"","page":"236","level":"1","children":[]},
  {"caption":"08-Rotary-EN","url":"","page":"288","level":"1","children":[]},
  {"caption":"09-Draw Latches-EN","url":"","page":"328","level":"1","children":[]},
  {"caption":"10-Hinges-EN","url":"","page":"368","level":"1","children":[]},
  {"caption":"11-Quarter-Turn-EN","url":"","page":"434","level":"1","children":[]},
  {"caption":"12-Captive Screws-EN","url":"","page":"516","level":"1","children":[]},
  {"caption":"13-Inject Eject-EN","url":"","page":"577","level":"1","children":[]},
  {"caption":"14-Handles and Pulls-EN","url":"","page":"598","level":"1","children":[]},
  {"caption":"15-Entry Door-EN","url":"","page":"611","level":"1","children":[]},
  {"caption":"16-Back-EN","url":"","page":"630","level":"1","children":[]},{"caption":"17-Back Cover-EN","url":"","page":636,"level":"1","children":[]}];

var bmtConfig = {
  "tabs":[
    {"caption":"Intro","pageIndex":3,"fontColor":"#ffffff","color":"#9D2235"},
    {"caption":"EAS","pageIndex":14,"fontColor":"#ffffff","color":"#2DBBDD"},
    {"caption":"Monitor Mounts ","pageIndex":58,"fontColor":"#ffffff","color":"#008E3D"},
    {"caption":"Compression","pageIndex":88,"fontColor":"#ffffff","color":"#00998C"},
    {"caption":"Cam Latches","pageIndex":148,"fontColor":"#ffffff","color":"#F7BF00"},
    {"caption":"Locks ","pageIndex":190,"fontColor":"#ffffff","color":"#5B6524"},
    {"caption":"Multi-Point","pageIndex":206,"fontColor":"#ffffff","color":"#ED8800"},
    {"caption":"Push to close","pageIndex":236,"fontColor":"#ffffff","color":"#5C257C"},
    {"caption":"Rotary","pageIndex":288,"fontColor":"#ffffff","color":"#006D75"},
    {"caption":"Draw Latches","pageIndex":328,"fontColor":"#ffffff","color":"#882159"},
    {"caption":"Hinges","pageIndex":368,"fontColor":"#ffffff","color":"#7AB729"},
    {"caption":"Quarter-Turn ","pageIndex":434,"fontColor":"#ffffff","color":"#00669B"},
    {"caption":"Captive Srews","pageIndex":516,"fontColor":"#ffffff","color":"#D41E21"},
    {"caption":"Inject Eject","pageIndex":577,"fontColor":"#ffffff","color":"#CB5A1E"},
    {"caption":"Handles and Pulls","pageIndex":598,"fontColor":"#ffffff","color":"#D9C300"},
    {"caption":"Entry Door ","pageIndex":611,"fontColor":"#ffffff","color":"#243063"},
    {"caption":"Index","pageIndex":635,"fontColor":"#ffffff","color":"#9D2235"}
  ],
  "hasTexture":false,
  "onSideEdge":true
};

var staticAd = {"haveAd":false,"adPosition":0,"adHeight":60,"interval":3000,"data":[]};
var videoList = [];
var slideshow = [];
var flipByAudio = {"audioType":0,"audioFile":"","showPlayer":false,"items":[]};
var phoneNumber = [];
var userList = {};

var search_pages = [{"index":0},{"index":634},{"index":1},{"index":2},{"index":3},{"index":4},{"index":5},{"index":6},{"index":7},{"index":8},{"index":9},{"index":10},{"index":11},{"index":12},{"index":13},{"index":14},{"index":15},{"index":16},{"index":17},{"index":18},{"index":19},{"index":20},{"index":21},{"index":22},{"index":23},{"index":24},{"index":25},{"index":26},{"index":27},{"index":28},{"index":29},{"index":30},{"index":31},{"index":32},{"index":33},{"index":34},{"index":35},{"index":36},{"index":37},{"index":38},{"index":39},{"index":40},{"index":41},{"index":42},{"index":43},{"index":44},{"index":45},{"index":46},{"index":47},{"index":48},{"index":49},{"index":50},{"index":51},{"index":52},{"index":53},{"index":54},{"index":55},{"index":56},{"index":57},{"index":58},{"index":59},{"index":60},{"index":61},{"index":62},{"index":63},{"index":64},{"index":65},{"index":66},{"index":67},{"index":68},{"index":69},{"index":70},{"index":71},{"index":72},{"index":73},{"index":74},{"index":75},{"index":76},{"index":77},{"index":78},{"index":79},{"index":80},{"index":81},{"index":82},{"index":83},{"index":84},{"index":85},{"index":86},{"index":87},{"index":88},{"index":89},{"index":90},{"index":91},{"index":92},{"index":93},{"index":94},{"index":95},{"index":96},{"index":97},{"index":98},{"index":99},{"index":100},{"index":101},{"index":102},{"index":103},{"index":104},{"index":105},{"index":106},{"index":107},{"index":108},{"index":109},{"index":110},{"index":111},{"index":112},{"index":113},{"index":114},{"index":115},{"index":116},{"index":117},{"index":118},{"index":119},{"index":120},{"index":121},{"index":122},{"index":123},{"index":124},{"index":125},{"index":126},{"index":127},{"index":128},{"index":129},{"index":130},{"index":131},{"index":132},{"index":133},{"index":134},{"index":135},{"index":136},{"index":137},{"index":138},{"index":139},{"index":140},{"index":141},{"index":142},{"index":143},{"index":144},{"index":145},{"index":146},{"index":147},{"index":148},{"index":149},{"index":150},{"index":151},{"index":152},{"index":153},{"index":154},{"index":155},{"index":156},{"index":157},{"index":158},{"index":159},{"index":160},{"index":161},{"index":162},{"index":163},{"index":164},{"index":165},{"index":166},{"index":167},{"index":168},{"index":169},{"index":170},{"index":171},{"index":172},{"index":173},{"index":174},{"index":175},{"index":176},{"index":177},{"index":178},{"index":179},{"index":180},{"index":181},{"index":182},{"index":183},{"index":184},{"index":185},{"index":186},{"index":187},{"index":188},{"index":189},{"index":190},{"index":191},{"index":192},{"index":193},{"index":194},{"index":195},{"index":196},{"index":197},{"index":198},{"index":199},{"index":200},{"index":201},{"index":202},{"index":203},{"index":204},{"index":205},{"index":206},{"index":207},{"index":208},{"index":209},{"index":210},{"index":211},{"index":212},{"index":213},{"index":214},{"index":215},{"index":216},{"index":217},{"index":218},{"index":219},{"index":220},{"index":221},{"index":222},{"index":223},{"index":224},{"index":225},{"index":226},{"index":227},{"index":228},{"index":229},{"index":230},{"index":231},{"index":232},{"index":233},{"index":234},{"index":235},{"index":236},{"index":237},{"index":238},{"index":239},{"index":240},{"index":241},{"index":242},{"index":243},{"index":244},{"index":245},{"index":246},{"index":247},{"index":248},{"index":249},{"index":250},{"index":251},{"index":252},{"index":253},{"index":254},{"index":255},{"index":256},{"index":257},{"index":258},{"index":259},{"index":260},{"index":261},{"index":262},{"index":263},{"index":264},{"index":265},{"index":266},{"index":267},{"index":268},{"index":269},{"index":270},{"index":271},{"index":272},{"index":273},{"index":274},{"index":275},{"index":276},{"index":277},{"index":278},{"index":279},{"index":280},{"index":281},{"index":282},{"index":283},{"index":284},{"index":285},{"index":286},{"index":287},{"index":288},{"index":289},{"index":290},{"index":291},{"index":292},{"index":293},{"index":294},{"index":295},{"index":296},{"index":297},{"index":298},{"index":299},{"index":300},{"index":301},{"index":302},{"index":303},{"index":304},{"index":305},{"index":306},{"index":307},{"index":308},{"index":309},{"index":310},{"index":311},{"index":312},{"index":313},{"index":314},{"index":315},{"index":316},{"index":317},{"index":318},{"index":319},{"index":320},{"index":321},{"index":322},{"index":323},{"index":324},{"index":325},{"index":326},{"index":327},{"index":328},{"index":329},{"index":330},{"index":331},{"index":332},{"index":333},{"index":334},{"index":335},{"index":336},{"index":337},{"index":338},{"index":339},{"index":340},{"index":341},{"index":342},{"index":343},{"index":344},{"index":345},{"index":346},{"index":347},{"index":348},{"index":349},{"index":350},{"index":351},{"index":352},{"index":353},{"index":354},{"index":355},{"index":356},{"index":357},{"index":358},{"index":359},{"index":360},{"index":361},{"index":362},{"index":363},{"index":364},{"index":365},{"index":366},{"index":367},{"index":368},{"index":369},{"index":370},{"index":371},{"index":372},{"index":373},{"index":374},{"index":375},{"index":376},{"index":377},{"index":378},{"index":379},{"index":380},{"index":381},{"index":382},{"index":383},{"index":384},{"index":385},{"index":386},{"index":387},{"index":388},{"index":389},{"index":390},{"index":391},{"index":392},{"index":393},{"index":394},{"index":395},{"index":396},{"index":397},{"index":398},{"index":399},{"index":400},{"index":401},{"index":402},{"index":403},{"index":404},{"index":405},{"index":406},{"index":407},{"index":408},{"index":409},{"index":410},{"index":411},{"index":412},{"index":413},{"index":414},{"index":415},{"index":416},{"index":417},{"index":418},{"index":419},{"index":420},{"index":421},{"index":422},{"index":423},{"index":424},{"index":425},{"index":426},{"index":427},{"index":428},{"index":429},{"index":430},{"index":431},{"index":432},{"index":433},{"index":434},{"index":435},{"index":436},{"index":437},{"index":438},{"index":439},{"index":440},{"index":441},{"index":442},{"index":443},{"index":444},{"index":445},{"index":446},{"index":447},{"index":448},{"index":449},{"index":450},{"index":451},{"index":452},{"index":453},{"index":454},{"index":455},{"index":456},{"index":457},{"index":458},{"index":459},{"index":460},{"index":461},{"index":462},{"index":463},{"index":464},{"index":465},{"index":466},{"index":467},{"index":468},{"index":469},{"index":470},{"index":471},{"index":472},{"index":473},{"index":474},{"index":475},{"index":476},{"index":477},{"index":478},{"index":479},{"index":480},{"index":481},{"index":482},{"index":483},{"index":484},{"index":485},{"index":486},{"index":487},{"index":488},{"index":489},{"index":490},{"index":491},{"index":492},{"index":493},{"index":494},{"index":495},{"index":496},{"index":497},{"index":498},{"index":499},{"index":500},{"index":501},{"index":502},{"index":503},{"index":504},{"index":505},{"index":506},{"index":507},{"index":508},{"index":509},{"index":510},{"index":511},{"index":512},{"index":513},{"index":514},{"index":515},{"index":516},{"index":517},{"index":518},{"index":519},{"index":520},{"index":521},{"index":522},{"index":523},{"index":524},{"index":525},{"index":526},{"index":527},{"index":528},{"index":529},{"index":530},{"index":531},{"index":532},{"index":533},{"index":534},{"index":535},{"index":536},{"index":537},{"index":538},{"index":539},{"index":540},{"index":541},{"index":542},{"index":543},{"index":544},{"index":545},{"index":546},{"index":547},{"index":548},{"index":549},{"index":550},{"index":551},{"index":552},{"index":553},{"index":554},{"index":555},{"index":556},{"index":557},{"index":558},{"index":559},{"index":560},{"index":561},{"index":562},{"index":563},{"index":564},{"index":565},{"index":566},{"index":567},{"index":568},{"index":569},{"index":570},{"index":571},{"index":572},{"index":573},{"index":574},{"index":575},{"index":576},{"index":577},{"index":578},{"index":579},{"index":580},{"index":581},{"index":582},{"index":583},{"index":584},{"index":585},{"index":586},{"index":587},{"index":588},{"index":589},{"index":590},{"index":591},{"index":592},{"index":593},{"index":594},{"index":595},{"index":596},{"index":597},{"index":598},{"index":599},{"index":600},{"index":601},{"index":602},{"index":603},{"index":604},{"index":605},{"index":606},{"index":607},{"index":608},{"index":609},{"index":610},{"index":611},{"index":612},{"index":613},{"index":614},{"index":615},{"index":616},{"index":617},{"index":618},{"index":619},{"index":620},{"index":621},{"index":622},{"index":623},{"index":624},{"index":625},{"index":626},{"index":627},{"index":628},{"index":629},{"index":630},{"index":631},{"index":632},{"index":636},{"index":633}];
var downloadconfig = {"pdf":{"isOriginPath":true,"url":"","urlOnlink":""},"isDownloadProject":false,"isDownloadAttach":false,"attachments":[]};
